version: '3.2'

services:
  invoice-scanner:
    build: 
      context: .
    ports:
      - '9292:9292'
      - '9293:9293'
    environment:
      ELASTIC_HOSTNAME: elasticsearch
      ELASTIC_PORT: 9200
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: changeme
    networks:
      - elk  
    depends_on:
      - elasticsearch  

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    volumes:
      - type: bind
        source: ./config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: '-Xmx256m -Xms256m'
      ELASTIC_PASSWORD: changeme
    networks:
      - elk
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.1
    volumes:
      - type: bind
        source: ./config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - '5601:5601'
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
    